INSERT INTO usuario(id, uuid, datahoraalteracao, datahorainclusao, usuarioalteracao, usuarioinclusao, versao, admin, ativo, bloqueado, email, validado, dataultimologin, nome, password) VALUES (19999, 'azsx1234556', current_timestamp, current_timestamp, 'admin@email.com.br', 'admin@email.com.br', 0, 'true', 'true', 'false', 'admin@email.com.br', 'true', null, 'admin', 'admin');
INSERT INTO papel(id, uuid, datahoraalteracao, datahorainclusao, usuarioalteracao, usuarioinclusao, versao, descricao, nomedopapel, ativo) VALUES (1, 'aasa1113', current_timestamp, current_timestamp, 'admin@email.com.br', 'admin@email.com.br', 0, 'Descrição teste', 'Admin', 'true');
INSERT INTO papel(id, uuid, datahoraalteracao, datahorainclusao, usuarioalteracao, usuarioinclusao, versao, descricao, nomedopapel, ativo) VALUES (2, 'aasa1113a', current_timestamp, current_timestamp, 'admin@email.com.br', 'admin@email.com.br', 0, 'Descrição teste', 'Usuario', 'true');
INSERT INTO papel(id, uuid, datahoraalteracao, datahorainclusao, usuarioalteracao, usuarioinclusao, versao, descricao, nomedopapel, ativo) VALUES (3, 'aasa1113b', current_timestamp, current_timestamp, 'admin@email.com.br', 'admin@email.com.br', 0, 'Descrição teste', 'Cliente', 'true');
INSERT INTO papeis_do_usuario(idusuario, idpapel) VALUES (19999, 1);

INSERT INTO store(id, uuid, datahoraalteracao, datahorainclusao, usuarioalteracao, usuarioinclusao, versao) VALUES (1000, '1000ab1', current_timestamp, current_timestamp, 'admin@email.com.br', 'admin@email.com.br', 0);
INSERT INTO place(id, uuid, datahoraalteracao, datahorainclusao, usuarioalteracao, usuarioinclusao, versao, name, idstore) VALUES (1000, '1000ab1', current_timestamp, current_timestamp, 'admin@email.com.br', 'admin@email.com.br', 0, 'Porta Principal', 1000);
INSERT INTO place(id, uuid, datahoraalteracao, datahorainclusao, usuarioalteracao, usuarioinclusao, versao, name, idstore) VALUES (1001, '1000ab2', current_timestamp, current_timestamp, 'admin@email.com.br', 'admin@email.com.br', 0, 'Açougue', 1000);
INSERT INTO place(id, uuid, datahoraalteracao, datahorainclusao, usuarioalteracao, usuarioinclusao, versao, name, idstore) VALUES (1002, '1000ab3', current_timestamp, current_timestamp, 'admin@email.com.br', 'admin@email.com.br', 0, 'Padaria', 1000);
INSERT INTO beacon(id, uuid, datahoraalteracao, datahorainclusao, usuarioalteracao, usuarioinclusao, versao, uuidbeacon, idplace) VALUES (1000, '1000a', current_timestamp, current_timestamp, 'admin@email.com.br', 'admin@email.com.br', 0, '1234567890',  1000);
INSERT INTO beacon(id, uuid, datahoraalteracao, datahorainclusao, usuarioalteracao, usuarioinclusao, versao, uuidbeacon, idplace) VALUES (1001, '1000b', current_timestamp, current_timestamp, 'admin@email.com.br', 'admin@email.com.br', 0, '1234567891',  1001);
INSERT INTO beacon(id, uuid, datahoraalteracao, datahorainclusao, usuarioalteracao, usuarioinclusao, versao, uuidbeacon, idplace) VALUES (1002, '1000c', current_timestamp, current_timestamp, 'admin@email.com.br', 'admin@email.com.br', 0, '1234567892',  1002);
